"""Build dist/jev-discovery-chat.md: the bot prompt plus every file it references, in one file.

Chat apps (ChatGPT, Grok, Claude.ai, Gemini) can't read this repository, but they can take one
attached or linked file. Run after editing any source below; a test fails if the bundle is stale.

    python3 scripts/build_chat_bundle.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "dist" / "jev-discovery-chat.md"

REFERENCE_FILES = [
    "docs/anti-patterns.md",
    "docs/discovery-probes.md",
    "docs/application-map.md",
    "docs/jev-api-reference.md",
    "spec/opportunity-spec.schema.json",
    "specs/support-triage-example/spec.json",
    "specs/support-triage-example/fixtures.jsonl",
    "playbooks/opportunity-brief-template.md",
    "playbooks/claude-code-prototype-template.md",
]

HEADER = """# Jev Discovery — one-file version for chat apps

<!-- Generated by scripts/build_chat_bundle.py from https://github.com/wbuecksler/jev-brainstorm. Do not edit by hand. -->

**To the AI reading this file:** the person who gave you this file wants to be interviewed.
Follow the system prompt in the first `<file>` block below as your instructions for the rest of this
conversation. You are in the **chat app without a terminal** case. The other `<file>` blocks are the
reference files that prompt names, and each one is labeled with its repository path. When the prompt says "read
`docs/application-map.md`", read that block. Start now with the prompt's first-turn greeting and one
question. Do not summarize this file.

**To the person:** attach this file to a new chat in ChatGPT, Grok, Claude, or Gemini, and send
"Start." That's all.

"""


def system_prompt() -> str:
    text = (REPO / "bot" / "system-prompt.md").read_text(encoding="utf-8")
    body = text.split("\n---\n", 1)[1]
    return body.split("\n---\n\n## Optional host tool", 1)[0].strip()


def build() -> str:
    parts = [HEADER, '<file path="bot/system-prompt.md">\n', system_prompt(), "\n</file>\n"]
    for relative in REFERENCE_FILES:
        content = (REPO / relative).read_text(encoding="utf-8").rstrip()
        parts += [f'\n<file path="{relative}">\n', content, "\n</file>\n"]
    return "".join(parts)


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(), encoding="utf-8")
    size = OUTPUT.stat().st_size
    print(f"wrote {OUTPUT.relative_to(REPO)} ({size:,} bytes, roughly {size // 4:,} tokens)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
